package cz.cvut.fel.bp.vyskojo1.database;

public class Data {

    public static void insertDataToDB(MyDatabaseHelper DB) {
        DB.addLesson(1, "beginner_images", "Na tomto snímku bylo něco upraveno. Vyberte část fotky, které se to týká.", "svalovec", 0, 4, "Upravená fotografie", "1", "2", "3", "4", "Sval tohoto borce není úplně pravý. Když se ho někdo pokusil v editoru zakulatit, podařilo se mu pokřivit i zeď v pozadí. ");
        DB.addLesson(1, "beginner_images", "Sex prý dobře prodává. Které z následujících reklam využívají ženské nebo mužské tělo k prodeji produktu, jenž s nimi nesouvisí?", "sex", 0, 1, "Tělo jako reklama", "První tři obrázky", "Poslední tři obrázky", "Pouze první dva obrázky", "Pouze poslední dva obrázky", "V reklamách, jako jsou tyto, je polonahé lidské tělo využito jako objekt, který má upoutat pozornost. Přímá souvislost s propagovanými produkty chybí. ");
        DB.addLesson(1, "beginner_images", "Notebook značky Apple byl do filmu Stážista umístěn:", "apple", 0, 2, "Reklama ve filmu", "Náhodně", "Záměrně, jako reklama na značku Apple.", "Jako vtip.", "Herečka umí jen s MacOS", "Firmy stojí o to, aby jejich produkty byly ve snímku viditelně umístěny, a jsou ochotné za to zaplatit. ");
        DB.addLesson(1, "beginner_images", "Co mají následující reklamy společné?", "mcdonald", 0, 1, "Rozkazy", "Říkají příjemcům sdělení, co by měli udělat.", "Odvolávají se na tradici produktů.", "Nic", "", "Mnoho reklam zdůrazňuje tradici výrobků, tyto dvě mezi ně ale nepatří. Usilují o to, aby se s nimi zákazníci ztotožnili. Přitom je oslovují a říkají jim, co mají dělat (všimněte si rozkazovacího způsobu). Coca Cola pro kampaň na českém trhu umístila na lahve 100 nejznámějších českých jmen. ");
        DB.addLesson(1, "beginner_images", "Věříte tomu, že ženy zachycené na snímku kráčely po ulici v okovech?", "okovy", 0, 2, "Víra", "Věřím", "Nevěřím", "Neumím se rozhodnout", "", "Ženy po této ulici skutečně šly, nikoliv ale v okovech. Řetěz byl do fotky přidán dodatečně. Fotomontáž se šířila na českých i zahraničních webech a také na sociálních sítích. Historii fotografií můžete ověřit jejich zpětným vyhledáváním na internetu, např. přes službu Google obrázky.");
        DB.addLesson(1, "beginner_images", "Pořádně se podívejte na tuto fotku. Dokážete poznat, kde byla vyfocena? ", "praha", 0, 3, "Řeka", "Benátky", "Hamburg", "Praha", "Budapešť", "Loď, která má na zádi nápis Praha a českou státní vlajku, nejpravděpodobněji uvidíte v Praze, kde jsou obvyklé i nápisy v angličtině cílící na turisty.");
        DB.addLesson(1, "beginner_texts", "Kdo jsou „internetoví trollové“? ", "", 0, 2, "Internetoví trollové", "Všichni uživatelé, kteří na internetu vystupují pod falešnou identitou.", "Uživatelé, kteří píšou na internetu urážlivé nebo nesouvisející příspěvky.","Uživatelé, kteří mají rádi fantasy příběhy.","Správci serverů.","Uživatelé, kteří píšou na internetu urážlivé nebo nesouvisející příspěvky.");
        DB.addLesson(1, "beginner_texts", "O návštěvě Andreje Babiše v Bílém domě bylo publikováno mnoho článků. Česká televize, Extra.cz (bulvární online portál) a Sputniknews (ruská státní zpravodajská agentura) zvolily stejnou fotografii, ale jiné titulky. Poznáte, který vyšel na Extra.cz?", "babis_trump", 0, 2, "Bulvár", "Babiš po přijetí v Bílém domě řekl, že s Trumpem navázal dobrý osobní vztah. ", "ŘEČ TĚLA A PENĚZ: Natěšený Andrej, netrpělivý Donald! Roli sehrálo i tučnější konto. ","Zapojíme se do války na Ukrajině: Okamura rozluštil prohlášení ze setkání Babiše s Trumpem.","","Čtenářům Extra.cz byl určen titulek o řeči těla a tučných kontech. První titulek je z České televize, třetí vydal Sputnik. Stejnou fotku dvou politiků každé médium titulkem tematicky „zarámovalo“ tak, aby zaujalo své typické čtenáře. ");
        DB.addLesson(1, "beginner_texts", "Který z následujících titulků nejpravděpodobněji ve čtenářích vzbudí dojem, že jezdit autem je nebezpečné?", "", 0, 2, "Titulek smrti", "Na silnicích v Česku zemřelo loni 571 z 10 miliónů občanů.", "Na silnici loni zemřelo v Česku 571 lidí. Oběťmi byly i nevinné děti.", "Loni byla v ČR pravděpodobnost úmrtí v důsledku dopravní nehody 0,00005396975 %.", "", "Matematicky věty vyjadřují totéž, psychologicky ale působí rozdílně.");
        DB.addLesson(1, "beginner_texts", "Jaký je rozdíl mezi novinářskými žánry „zpráva“ a „komentář“?", "", 0, 3, "Zpráva nebo komentář?", "Žádný, obojí poskytují fakta o aktuálním dění.", "Zprávy jsou publikovány v tištěných novinách i na zpravodajských webech, komentáře pouze na internetu.", "Zpráva nesděluje, jaké názory má na danou událost nebo problém její autor, komentář ano. ", "", "Zpráva nesděluje, jaké názory má na danou událost nebo problém její autor, komentář ano. ");
        DB.addLesson(1, "beginner_texts", "Co je to „fake news“?", "", 0, 2, "Fake news", "Anglický výraz pro zprávy v komerčních médiích.", "Nepravdivá nebo částečně nepravdivá zpráva.", "Obecné označení zpráv od neznámého autora.", "", "Nepravdivá nebo částečně nepravdivá zpráva.");
        DB.addLesson(1, "beginner_texts", "Co je pro provozovatele webů hlavním důvodem pro umisťování online reklamy na webové stránky? ", "", 0, 2, "Online reklama", "Chtějí doporučit návštěvníkům svého webu ty nejlepší produkty a služby.", "Za umístěnou reklamu získávají peníze. ", "Zaplňují tak prostor, který by byl jinak nevyužitý.", "Internetové vyhledavače stránky s reklamami zobrazují přednostně.", "Za umístěnou reklamu získávají peníze. ");
        DB.addLesson(1, "beginner_texts", "Co je tisková zpráva?", "", 0, 2, "Tisková zpráva", "Informace o hospodaření, kterou musí podle zákona pravidelně vydávat každé tištěné periodikum.", "Zpráva, kterou vydává nějaká firma, politická strana či jiná organizace s cílem sdělit něco veřejnosti.", "Zpráva, která se objevuje výhradně v tištěných médiích.", "", "Zpráva, kterou vydává nějaká firma, politická strana či jiná organizace s cílem sdělit něco veřejnosti.");
        DB.addLesson(1, "beginner_graphs", "Následující graf ukazuje, jak dopadla volba předsedy hnutí Pro. Poznáte pouze z grafického vyjádření, kdo získal nejvíc hlasů? Pokud ne, tipněte si. ", "pro", 0, 2, "Volba předsedy", "Antonín Celerín", "Malvína Jůblová", "Ambrož Hinz", "Konrád Pudil", "Že to bylo těžké poznat? Máte pravdu, koláčový graf je pro zobrazení velmi malých rozdílů nevhodný. Lépe by byly vidět ve sloupcovém grafu. ");
        DB.addLesson(1, "beginner_graphs", "Následující mapa porovnává míru kriminality v jednotlivých krajích ČR. Co na ní nesedí?", "mapa", 0, 3, "Mapa", "Kvůli ochraně dat nelze kriminalitu vyhodnocovat po krajích.", "Více vypovídající by bylo, kdyby byl počet trestných činů vyjádřen v absolutních číslech. ", "Barvy na škále jsou obráceně, než bývá zvykem.", "", "Bývá zvykem užívat pro znázornění většího počtu nebo koncentrace tmavší či sytější barvy. Obrácení škály může čtenáře vést k mylné interpretaci (např., že v Praze je nižší kriminalita než v Pardubickém kraji). ");
        DB.addLesson(1, "advanced_images", "Sdělení, které vidíte, je:", "az", 0, 3, "AZ247", "Zpravodajství", "Infotainment", "Satira", "", "Satira je žánr využívající komičnosti, výsměchu, karikatury a ironie. Web AZ247.cz publikuje vymyšlené články, které mají parodovat zpravodajství dezinformačních webů. ");
        DB.addLesson(1, "advanced_images", "Který z následujících tweetů je důvěryhodnější?", "tweet", 0, 1, "Tweety", "Nelze určit.", "Tweet 1 s fotkou.", "Tweet 2 bez fotky.", "", "To, že je u příspěvku fotografie, nezvyšuje automaticky jeho důvěryhodnost. Fotka doprovázející text může být upravená v grafickém editoru nebo pořízená jindy a jinde. Pokud vyhledáme historii této konkrétní fotky (např. přes Google Images), zjistíme, že byla vyfocena na Mistrovství Evropy ve fotbale v roce 2016. Ani jeden z tweetů nelze proto hodnotit jako důvěryhodný.");
        DB.addLesson(1, "advanced_images", "Věříte na základě článku níže tomu, že Američané chtějí odlidnit planetu pomocí rozprašování chemtrails?", "chemtrails", 0, 2, "Chemtrails", "Věřím", "Nevěřím", "Neumím se rozhodnout", "", "Chemtrails je jedna z nejrozšířenějších konspiračních teorií, která se poprvé objevila na konci 90. let. Podle konspiračních teorií se mnohé věci odehrávají kvůli spiknutí mocných osob nebo celých vlád. V případě chemtrails jsou absurdní i rady, jak se před jejich dopadem chránit: stačí prý nastříkat ocet na silnici a nechat ho vypařit do atmosféry.");
        DB.addLesson(1, "advanced_images", "Podívejte se na tuto fotku. Který popisek k ní podle vás sedí?", "datumy", 0, 2, "Datum", "Oslava státního svátku 28. září.", "Uctění památky Václava Havla 18. prosince.", "Uctění památky mistra Jana Husa 6. července.", "", "Sníh a vánoční stromky v pozadí na náměstích v červenci ani v září nebývají. Kombinace „pravá fotografie, ale nepravdivý popisek“ je jednou z nejčastějších technik, které využívají autoři falešných zpráv.");
        DB.addLesson(1, "advanced_images", "Fotky do časopisů se často upravují, aby vypadaly co nejlépe. U této však po editaci zůstala chyba odporující logice. Označte číslo pole, v němž se nachází. ", "casopis", 0, 3, "Časopis", "1", "2", "3", "4", "Žena v černých šatech má dvě levé ruce, jednu na klíně a druhou kolem pasu blonďaté dívky. ");
        DB.addLesson(1, "advanced_images", "Níže vidíte několik fotek se stejným mužem. Na které webové stránce se objevila poprvé? ", "muz", 0, 2, "Tajemný muž", "1", "3", "5", "6", "Shutterstock je jednou z nejznámějších fotobank. Muž z fotek jí prodal práva na své fotky, tvůrci webových obsahů a reklam si je v databázi fotobanky následně našli, odkoupili a využili pro marketingové účely. ");
        DB.addLesson(1, "advanced_texts", "U autora článku vidíme písmena ČTK. Co znamenají? ", "ctk", 0, 3, "ČTK", "Je to zkratka jména autora – Čestmír Kroupa, tzv. šifra.", "Je to pseudonym autora, který chce zůstat v anonymitě.", "Je to zkratka České tiskové kanceláře.", "", "ČTK je ustálená zkratka pro Českou tiskovou kancelář, což je tisková informační agentura, od níž média získávají zprávy. Je s Českou televizí a Českým rozhlasem jedním z médií veřejné služby.");
        DB.addLesson(1, "advanced_texts", "Zvýrazněný článek je: ", "clanek", 0, 2, "Článek", "Zpráva", "Reklama", "Komentář", "", "Označení „obchodní sdělení“ znamená, že článek slouží k propagaci produktů, v tomto případě firmy Canon. Někdy se pro podobná sdělení využívá označení „komerční sdělení“ nebo „PR článek“.");
        DB.addLesson(1, "advanced_texts", "Co je podmínkou pro to, aby člověk mohl v ČR oficiálně pracovat jako novinář? ", "", 0, 4, "Novinář", "Studium žurnalistiky.", "Členství v Syndikátu novinářů.", "Složení zkoušky z českého jazyka.", "Nic z výše uvedeného.", "Nic z výše uvedeného.");
        DB.addLesson(1, "advanced_texts", "Mohu napsat na Facebook vymyšlenou zprávu, že skupina osmdesáti arabských mladíků útočí v Pardubicích na důchodce s nožem v ruce?", "", 0, 2, "Důchodci", "Ano, svoboda projevu nemá na Facebooku žádné hranice.", "Ano, ale mohu být obviněn z trestného činu „šíření poplašné zprávy“.", "Ano, ale moc dlouho tam nezůstane, Facebook všechny příspěvky ověřuje a ty nepravdivé do 5 minut smaže.", "", "Svoboda projevu má své hranice, které jsou vymezeny zákony. Platí o pro příspěvky na sociálních sítích.");
        DB.addLesson(1, "advanced_texts", "Kdy ve světě odstartovalo první pravidelné televizní vysílání? ", "", 0, 3, "Televize", "V 40. letech 19. století.", "V 70. letech 19. století.", "V 30. letech 20. století.", "V 70. letech 20. století.", "Bylo to v roce 1935 v Německu, v roce 1936 začala vysílat BBC ve Velké Británii.");
        DB.addLesson(1, "advanced_texts", "Jaká reklama v ČR nesmí být podle zákona zaměřena na mladší osoby 18 let? ", "", 0, 1, "Reklamy v ČR", "Na hazardní hry.", "Na bankovní produkty.", "Na sladkosti.", "Reklama v ČR není nijak regulována.", "Ukládá jí to zákon o regulaci reklamy. Stejné omezení platí pro tabákové výrobky nebo alkohol. ");
        DB.addLesson(1, "advanced_texts", "Co je deepfake?", "", 0, 3, "Deepfake", "Jakákoliv poplašná zpráva, která může vyvolat paniku.", "Uživatelé sociálních sítí, kteří mají více než 10 falešných profilů.", "Produkce velmi věrohodně vypadajících videí, obrázků nebo zvukových souborů, které jsou vydávány za reálné. ", "", "Deepfake vytvářejí nástroje využívající prvky umělé inteligence. Ve videích dovedou změnit obličej, hlas i vložit postavám do úst věty, které nikdy nevyslovily. Např. video, v němž Tomio Okamura propaguje přijetí eura. Nebezpečí deepfake spočívá v tom, že často nelze poznat, že jde o podvod. ");
        DB.addLesson(1, "advanced_texts", "Jaké médium nespadá do koncernu Agrofert, který založil Andrej Babiš a v roce 2017 převedl do správy svěřenských fondů?", "", 0, 2, "Média", "Deník Lidové noviny ", "Časopis Týden", "Web iDNES.cz ", "Bezplatný deník Metro ", "Časopis Týden patří do vydavatelství Empresa Media, které založil a vlastní Jaromír Soukup. Ostatní média patří do mediálního domu Mafra, který byl koupen Agrofertem v roce 2013. ");
        DB.addLesson(1, "advanced_graphs", "Podle následujícího grafu existuje souvislost mezi konzumací zmrzliny a počtem lidí, kteří se utopí. Co je na něm podle vás v nepořádku?", "zmrzlina", 0, 3, "Utopen ve zmrzlině", "Tento trend by bylo potřeba sledovat delší dobu.", "Prezentovaná data jsou chybná. Zmrzlinu jí rozhodně více lidí, než kolik umírá utonutím. ", "Graf uměle vytváří vztah mezi dvěma nesouvisejícími jevy.", "", "V létě jedí lidé nejčastěji zmrzlinu a také se chodí nejčastěji koupat, protože je horko a chtějí se ochladit. Někteří při koupání bohužel utonou. Mezi samotným pojídáním zmrzliny a počtem utonutých lidí však není žádný příčinný vztah, zvýšení jednoho nemá vliv na druhé.");
        DB.addLesson(1, "advanced_graphs", "Titulní strana časopisu z ledna 2017 znázorňuje počet žádostí o azyl v Evropě v letech 2013, 2015 a odhad na 2017. Co je na ní problematické?", "azyl", 0, 2, "Azyl", "Porušuje zákonný požadavek na dodržování vyváženosti a objektivity.", "Navozuje dojem, že všichni žadatelé o azyl jsou muslimové.", "Nic", "", "Titulní strana klame v mnoha ohledech. Více vypovídající by byla, kdyby použila následující graf, v němž jsou zařazeny i roky 2014 a 2016. Dnes už víme, kolik lidí požádalo o azyl v roce 2017, bylo to 704.600 lidí. Toto číslo se blíží ke stavu z roku 2014. Zákonný požadavek dodržovat ve zpravodajství vyváženost a objektivitu se vztahuje pouze na rozhlasové a televizní stanice. ");
        DB.addLesson(1, "advanced_graphs", "Následující zpráva informuje o vývoji ceny benzínu v květnu 2016. Titulek je zavádějící, proč?", "benzin", 0, 3, "Ceny benzínu", "Vývoj cen by se měl sledovat po měsících.", "Cena benzínu souvisí s cenou nafty, která není uvedena.", "Měřítko na ose Y je příliš jemné, takže kolísání cen vypadá dramatičtěji než ve skutečnosti. ", "", "Když zobrazíme vývoj cen se směrodatnějším měřítkem, je lépe vidět, že rozdíly v ceně benzínu byly ve sledovaném období minimální a pro běžného uživatele bezvýznamné. ");
    }

}
